In [ ]:
#basic broadcasting example
import numpy as np
a=np.array([1,2,3])
b=2
print(a+b)

In [7]:
#outer addition
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30])
print(a[:,np.newaxis]+b)
print(a[:,np.newaxis]+b[np.newaxis,:])
#print(a[:,np.newaxis]+b[:,np.newaxis])--> will produce error



[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


In [9]:
#for vector quantization algorithm--> example
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])  #weight and height of an athlete
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])          # weight and height of 4 clusters
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
print(diff)
print(dist)                    #shortest distance gives the best matching cluster
print("The best match is index: ",argmin(dist))

[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]]
[17.49285568 21.58703314 73.79024326 56.04462508]
The best match is index:  0


In [16]:
#universal functions example
#reduce method
import numpy as np
a=np.arange(9).reshape(3,3)
print("Array:\n",a)
print("1.\n",np.add.reduce(a,0))  #column wise addition
print("2.\n",np.add.reduce(a,1))  #row wise addition
print("5.\n",np.add.reduce(a,(0,1)))  #column wise multiplication
print("3.\n",np.add.accumulate(a,1)) #row wise cumulative addition
print("4.\n",np.multiply.accumulate(a,0)) #column wise cumulative multiplication

Array:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
1.
 [ 9 12 15]
2.
 [ 3 12 21]
5.
 36
3.
 [[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]
4.
 [[ 0  1  2]
 [ 0  4 10]
 [ 0 28 80]]


In [17]:
#safe type casting example
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()

print_table(np.typecodes['All'])

X ? b h i l q n p B H I L Q N P e f d g F D G S U V O M m
? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y Y - - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y Y - - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - Y Y Y Y Y - - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - - Y Y Y - - - - - - - - - Y Y - Y Y Y Y Y Y - Y
n - - - - - Y Y Y - - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - - Y Y Y - - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y Y - Y Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - - Y Y Y - - Y Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - Y Y Y - - Y Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
Q - - - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
N - - - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - 