In [ ]:
#basic broadcasting example
import numpy as np
a=np.array([1,2,3])
b=2
print(a+b)

In [7]:
#outer addition
import numpy as np
a=np.array([1,2,3,4])
b=np.array([10,20,30])
print(a[:,np.newaxis]+b)
print(a[:,np.newaxis]+b[np.newaxis,:])
#print(a[:,np.newaxis]+b[:,np.newaxis])--> will produce error



[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]
[[11 21 31]
 [12 22 32]
 [13 23 33]
 [14 24 34]]


In [9]:
#for vector quantization algorithm--> example
from numpy import array, argmin, sqrt, sum
observation = array([111.0, 188.0])  #weight and height of an athlete
codes = array([[102.0, 203.0],
               [132.0, 193.0],
               [45.0, 155.0],
               [57.0, 173.0]])          # weight and height of 4 clusters
diff = codes - observation    # the broadcast happens here
dist = sqrt(sum(diff**2,axis=-1))
print(diff)
print(dist)                    #shortest distance gives the best matching cluster
print("The best match is index: ",argmin(dist))

[[ -9.  15.]
 [ 21.   5.]
 [-66. -33.]
 [-54. -15.]]
[17.49285568 21.58703314 73.79024326 56.04462508]
The best match is index:  0
