In [1]:
import numpy as np
a=np.arange(40,100,3).reshape(4,5)
print(a)

[[40 43 46 49 52]
 [55 58 61 64 67]
 [70 73 76 79 82]
 [85 88 91 94 97]]


In [2]:
a[1,2]

np.int64(61)

In [3]:
a[::-1, ::-1]

array([[97, 94, 91, 88, 85],
       [82, 79, 76, 73, 70],
       [67, 64, 61, 58, 55],
       [52, 49, 46, 43, 40]])

In [4]:
a[:,1]

array([43, 58, 73, 88])

In [5]:
a[0, :]

array([40, 43, 46, 49, 52])

In [6]:
a[:,:]

array([[40, 43, 46, 49, 52],
       [55, 58, 61, 64, 67],
       [70, 73, 76, 79, 82],
       [85, 88, 91, 94, 97]])

In [7]:
a[::2,::2]=10000
print(a)

[[10000    43 10000    49 10000]
 [   55    58    61    64    67]
 [10000    73 10000    79 10000]
 [   85    88    91    94    97]]
