In [2]:
import numpy as np
a = np.arange(10).reshape(5,2)
print(a)
print(a.ravel())

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[0 1 2 3 4 5 6 7 8 9]


In [3]:
print(a.T)
print(a.T.shape)

[[0 2 4 6 8]
 [1 3 5 7 9]]
(2, 5)


In [3]:
import numpy as np
a = np.arange(10).reshape(5,2)
print("Original Array:\n",a)
a= a.copy()
a.resize((1,2))
print("1.\n",a)

Original Array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
1.
 [[0 1]]


In [ ]:
a=np.arange(10,30,2).reshape(5,2)
b= np.arange(10).reshape(5,2)
print("Original Array a:\n",a)
print("Original Array b:\n",b)
print("1.\n",np.vstack((a,b)))
print("2.\n",np.hstack((a,b)))


Original Array a:
 [[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]]
Original Array b:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
1.
 [[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]
2.
 [[10 12  0  1]
 [14 16  2  3]
 [18 20  4  5]
 [22 24  6  7]
 [26 28  8  9]]
3.
 [[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]


In [11]:
print("3.\n",np.concatenate((a,b),axis=0))

3.
 [[10 12]
 [14 16]
 [18 20]
 [22 24]
 [26 28]
 [ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]]
