In [2]:
import numpy as np
a= np.arange(10).reshape(5,2)
b= np.arange(10,30,2).reshape(5,2)
c= a-b
print(c)

[[-10 -11]
 [-12 -13]
 [-14 -15]
 [-16 -17]
 [-18 -19]]


In [4]:
print(c>0)

[[False False]
 [False False]
 [False False]
 [False False]
 [False False]]


In [5]:
print(b**2)

[[100 144]
 [196 256]
 [324 400]
 [484 576]
 [676 784]]


In [9]:
print("Element mult-->\n",a*b)
print("Matrix mult-->\n",np.dot(a,b.T))

Element mult-->
 [[  0  12]
 [ 28  48]
 [ 72 100]
 [132 168]
 [208 252]]
Matrix mult-->
 [[ 12  16  20  24  28]
 [ 56  76  96 116 136]
 [100 136 172 208 244]
 [144 196 248 300 352]
 [188 256 324 392 460]]


In [11]:
print(a.sum()) #sum of all elements
print(a.sum(axis=0)) #sum of each column
print(a.cumsum()) #cumulative sum of all elements
print(a.cumsum(axis=0)) #cumulative sum of each column
print(a.min()) #minimum element
print(a.max()) #maximum element
print(a.mean()) #mean of all elements


45
[20 25]
[ 0  1  3  6 10 15 21 28 36 45]
[[ 0  1]
 [ 2  4]
 [ 6  9]
 [12 16]
 [20 25]]
0
9
4.5
